/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Predator_s.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[0.22, 0.22, 0.22]}>
        <mesh geometry={nodes.mesh0.geometry} material={materials.cabeza} />
        <mesh geometry={nodes.mesh0_dat_polySurface13_1.geometry} material={materials.cuerpo} />
        <mesh geometry={nodes.mesh0_1.geometry} material={materials.casco} />
      </group>
    </group>
  )
}

useGLTF.preload('/Predator_s.glb')
